//
// Autogenerated by Thrift Compiler (0.8.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
var Thrift = require('thrift').Thrift;

var ttypes = require('./Bombah_types');
//HELPER FUNCTIONS AND STRUCTURES

var BombahService_ping_args = function(args) {
};
BombahService_ping_args.prototype = {};
BombahService_ping_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BombahService_ping_args.prototype.write = function(output) {
  output.writeStructBegin('BombahService_ping_args');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BombahService_ping_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
  }
};
BombahService_ping_result.prototype = {};
BombahService_ping_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRING) {
        this.success = input.readString();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BombahService_ping_result.prototype.write = function(output) {
  output.writeStructBegin('BombahService_ping_result');
  if (this.success) {
    output.writeFieldBegin('success', Thrift.Type.STRING, 0);
    output.writeString(this.success);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BombahService_controllerEvent_args = function(args) {
  this.playerId = null;
  this.controllerState = null;
  if (args) {
    if (args.playerId !== undefined) {
      this.playerId = args.playerId;
    }
    if (args.controllerState !== undefined) {
      this.controllerState = args.controllerState;
    }
  }
};
BombahService_controllerEvent_args.prototype = {};
BombahService_controllerEvent_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.playerId = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.controllerState = new ttypes.ControllerState();
        this.controllerState.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BombahService_controllerEvent_args.prototype.write = function(output) {
  output.writeStructBegin('BombahService_controllerEvent_args');
  if (this.playerId) {
    output.writeFieldBegin('playerId', Thrift.Type.I32, 1);
    output.writeI32(this.playerId);
    output.writeFieldEnd();
  }
  if (this.controllerState) {
    output.writeFieldBegin('controllerState', Thrift.Type.STRUCT, 2);
    this.controllerState.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BombahService_controllerEvent_result = function(args) {
  this.success = null;
  this.youAreDead = null;
  this.gameOver = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.youAreDead !== undefined) {
      this.youAreDead = args.youAreDead;
    }
    if (args.gameOver !== undefined) {
      this.gameOver = args.gameOver;
    }
  }
};
BombahService_controllerEvent_result.prototype = {};
BombahService_controllerEvent_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.ControllerResult();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.youAreDead = new ttypes.YouAreDeadException();
        this.youAreDead.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.gameOver = new ttypes.GameOverException();
        this.gameOver.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BombahService_controllerEvent_result.prototype.write = function(output) {
  output.writeStructBegin('BombahService_controllerEvent_result');
  if (this.success) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.youAreDead) {
    output.writeFieldBegin('youAreDead', Thrift.Type.STRUCT, 1);
    this.youAreDead.write(output);
    output.writeFieldEnd();
  }
  if (this.gameOver) {
    output.writeFieldBegin('gameOver', Thrift.Type.STRUCT, 2);
    this.gameOver.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BombahService_move_args = function(args) {
  this.playerId = null;
  this.moveAction = null;
  if (args) {
    if (args.playerId !== undefined) {
      this.playerId = args.playerId;
    }
    if (args.moveAction !== undefined) {
      this.moveAction = args.moveAction;
    }
  }
};
BombahService_move_args.prototype = {};
BombahService_move_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.playerId = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.moveAction = new ttypes.MoveAction();
        this.moveAction.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BombahService_move_args.prototype.write = function(output) {
  output.writeStructBegin('BombahService_move_args');
  if (this.playerId) {
    output.writeFieldBegin('playerId', Thrift.Type.I32, 1);
    output.writeI32(this.playerId);
    output.writeFieldEnd();
  }
  if (this.moveAction) {
    output.writeFieldBegin('moveAction', Thrift.Type.STRUCT, 2);
    this.moveAction.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BombahService_move_result = function(args) {
  this.success = null;
  this.youAreDead = null;
  this.gameOver = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.youAreDead !== undefined) {
      this.youAreDead = args.youAreDead;
    }
    if (args.gameOver !== undefined) {
      this.gameOver = args.gameOver;
    }
  }
};
BombahService_move_result.prototype = {};
BombahService_move_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.MoveActionResult();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.youAreDead = new ttypes.YouAreDeadException();
        this.youAreDead.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.gameOver = new ttypes.GameOverException();
        this.gameOver.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BombahService_move_result.prototype.write = function(output) {
  output.writeStructBegin('BombahService_move_result');
  if (this.success) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.youAreDead) {
    output.writeFieldBegin('youAreDead', Thrift.Type.STRUCT, 1);
    this.youAreDead.write(output);
    output.writeFieldEnd();
  }
  if (this.gameOver) {
    output.writeFieldBegin('gameOver', Thrift.Type.STRUCT, 2);
    this.gameOver.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BombahService_bomb_args = function(args) {
  this.playerId = null;
  this.bombAction = null;
  if (args) {
    if (args.playerId !== undefined) {
      this.playerId = args.playerId;
    }
    if (args.bombAction !== undefined) {
      this.bombAction = args.bombAction;
    }
  }
};
BombahService_bomb_args.prototype = {};
BombahService_bomb_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.playerId = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.bombAction = new ttypes.BombAction();
        this.bombAction.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BombahService_bomb_args.prototype.write = function(output) {
  output.writeStructBegin('BombahService_bomb_args');
  if (this.playerId) {
    output.writeFieldBegin('playerId', Thrift.Type.I32, 1);
    output.writeI32(this.playerId);
    output.writeFieldEnd();
  }
  if (this.bombAction) {
    output.writeFieldBegin('bombAction', Thrift.Type.STRUCT, 2);
    this.bombAction.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BombahService_bomb_result = function(args) {
  this.success = null;
  this.youAreDead = null;
  this.gameOver = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.youAreDead !== undefined) {
      this.youAreDead = args.youAreDead;
    }
    if (args.gameOver !== undefined) {
      this.gameOver = args.gameOver;
    }
  }
};
BombahService_bomb_result.prototype = {};
BombahService_bomb_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.BombActionResult();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.youAreDead = new ttypes.YouAreDeadException();
        this.youAreDead.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.gameOver = new ttypes.GameOverException();
        this.gameOver.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BombahService_bomb_result.prototype.write = function(output) {
  output.writeStructBegin('BombahService_bomb_result');
  if (this.success) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.youAreDead) {
    output.writeFieldBegin('youAreDead', Thrift.Type.STRUCT, 1);
    this.youAreDead.write(output);
    output.writeFieldEnd();
  }
  if (this.gameOver) {
    output.writeFieldBegin('gameOver', Thrift.Type.STRUCT, 2);
    this.gameOver.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BombahService_waitTicks_args = function(args) {
  this.gameId = null;
  this.ticks = null;
  if (args) {
    if (args.gameId !== undefined) {
      this.gameId = args.gameId;
    }
    if (args.ticks !== undefined) {
      this.ticks = args.ticks;
    }
  }
};
BombahService_waitTicks_args.prototype = {};
BombahService_waitTicks_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.gameId = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.ticks = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BombahService_waitTicks_args.prototype.write = function(output) {
  output.writeStructBegin('BombahService_waitTicks_args');
  if (this.gameId) {
    output.writeFieldBegin('gameId', Thrift.Type.I32, 1);
    output.writeI32(this.gameId);
    output.writeFieldEnd();
  }
  if (this.ticks) {
    output.writeFieldBegin('ticks', Thrift.Type.I32, 2);
    output.writeI32(this.ticks);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BombahService_waitTicks_result = function(args) {
  this.success = null;
  this.youAreDead = null;
  this.gameOver = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.youAreDead !== undefined) {
      this.youAreDead = args.youAreDead;
    }
    if (args.gameOver !== undefined) {
      this.gameOver = args.gameOver;
    }
  }
};
BombahService_waitTicks_result.prototype = {};
BombahService_waitTicks_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.MapState();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.youAreDead = new ttypes.YouAreDeadException();
        this.youAreDead.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.gameOver = new ttypes.GameOverException();
        this.gameOver.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BombahService_waitTicks_result.prototype.write = function(output) {
  output.writeStructBegin('BombahService_waitTicks_result');
  if (this.success) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.youAreDead) {
    output.writeFieldBegin('youAreDead', Thrift.Type.STRUCT, 1);
    this.youAreDead.write(output);
    output.writeFieldEnd();
  }
  if (this.gameOver) {
    output.writeFieldBegin('gameOver', Thrift.Type.STRUCT, 2);
    this.gameOver.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BombahService_waitForTick_args = function(args) {
  this.gameId = null;
  this.tick = null;
  if (args) {
    if (args.gameId !== undefined) {
      this.gameId = args.gameId;
    }
    if (args.tick !== undefined) {
      this.tick = args.tick;
    }
  }
};
BombahService_waitForTick_args.prototype = {};
BombahService_waitForTick_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.gameId = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.I32) {
        this.tick = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BombahService_waitForTick_args.prototype.write = function(output) {
  output.writeStructBegin('BombahService_waitForTick_args');
  if (this.gameId) {
    output.writeFieldBegin('gameId', Thrift.Type.I32, 1);
    output.writeI32(this.gameId);
    output.writeFieldEnd();
  }
  if (this.tick) {
    output.writeFieldBegin('tick', Thrift.Type.I32, 2);
    output.writeI32(this.tick);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BombahService_waitForTick_result = function(args) {
  this.success = null;
  this.youAreDead = null;
  this.gameOver = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.youAreDead !== undefined) {
      this.youAreDead = args.youAreDead;
    }
    if (args.gameOver !== undefined) {
      this.gameOver = args.gameOver;
    }
  }
};
BombahService_waitForTick_result.prototype = {};
BombahService_waitForTick_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.MapState();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.youAreDead = new ttypes.YouAreDeadException();
        this.youAreDead.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 2:
      if (ftype == Thrift.Type.STRUCT) {
        this.gameOver = new ttypes.GameOverException();
        this.gameOver.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BombahService_waitForTick_result.prototype.write = function(output) {
  output.writeStructBegin('BombahService_waitForTick_result');
  if (this.success) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.youAreDead) {
    output.writeFieldBegin('youAreDead', Thrift.Type.STRUCT, 1);
    this.youAreDead.write(output);
    output.writeFieldEnd();
  }
  if (this.gameOver) {
    output.writeFieldBegin('gameOver', Thrift.Type.STRUCT, 2);
    this.gameOver.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BombahService_joinGame_args = function(args) {
  this.gameId = null;
  if (args) {
    if (args.gameId !== undefined) {
      this.gameId = args.gameId;
    }
  }
};
BombahService_joinGame_args.prototype = {};
BombahService_joinGame_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.gameId = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BombahService_joinGame_args.prototype.write = function(output) {
  output.writeStructBegin('BombahService_joinGame_args');
  if (this.gameId) {
    output.writeFieldBegin('gameId', Thrift.Type.I32, 1);
    output.writeI32(this.gameId);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BombahService_joinGame_result = function(args) {
  this.success = null;
  this.gameOverException = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.gameOverException !== undefined) {
      this.gameOverException = args.gameOverException;
    }
  }
};
BombahService_joinGame_result.prototype = {};
BombahService_joinGame_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.GameInfo();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.gameOverException = new ttypes.GameOverException();
        this.gameOverException.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BombahService_joinGame_result.prototype.write = function(output) {
  output.writeStructBegin('BombahService_joinGame_result');
  if (this.success) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.gameOverException) {
    output.writeFieldBegin('gameOverException', Thrift.Type.STRUCT, 1);
    this.gameOverException.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BombahService_getGameInfo_args = function(args) {
  this.gameId = null;
  if (args) {
    if (args.gameId !== undefined) {
      this.gameId = args.gameId;
    }
  }
};
BombahService_getGameInfo_args.prototype = {};
BombahService_getGameInfo_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.gameId = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BombahService_getGameInfo_args.prototype.write = function(output) {
  output.writeStructBegin('BombahService_getGameInfo_args');
  if (this.gameId) {
    output.writeFieldBegin('gameId', Thrift.Type.I32, 1);
    output.writeI32(this.gameId);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BombahService_getGameInfo_result = function(args) {
  this.success = null;
  this.gameOverException = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.gameOverException !== undefined) {
      this.gameOverException = args.gameOverException;
    }
  }
};
BombahService_getGameInfo_result.prototype = {};
BombahService_getGameInfo_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.GameInfo();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.gameOverException = new ttypes.GameOverException();
        this.gameOverException.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BombahService_getGameInfo_result.prototype.write = function(output) {
  output.writeStructBegin('BombahService_getGameInfo_result');
  if (this.success) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.gameOverException) {
    output.writeFieldBegin('gameOverException', Thrift.Type.STRUCT, 1);
    this.gameOverException.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BombahService_debugResetGame_args = function(args) {
  this.gameId = null;
  if (args) {
    if (args.gameId !== undefined) {
      this.gameId = args.gameId;
    }
  }
};
BombahService_debugResetGame_args.prototype = {};
BombahService_debugResetGame_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.gameId = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BombahService_debugResetGame_args.prototype.write = function(output) {
  output.writeStructBegin('BombahService_debugResetGame_args');
  if (this.gameId) {
    output.writeFieldBegin('gameId', Thrift.Type.I32, 1);
    output.writeI32(this.gameId);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BombahService_debugResetGame_result = function(args) {
};
BombahService_debugResetGame_result.prototype = {};
BombahService_debugResetGame_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    input.skip(ftype);
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BombahService_debugResetGame_result.prototype.write = function(output) {
  output.writeStructBegin('BombahService_debugResetGame_result');
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BombahService_waitForStart_args = function(args) {
  this.gameId = null;
  if (args) {
    if (args.gameId !== undefined) {
      this.gameId = args.gameId;
    }
  }
};
BombahService_waitForStart_args.prototype = {};
BombahService_waitForStart_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.gameId = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BombahService_waitForStart_args.prototype.write = function(output) {
  output.writeStructBegin('BombahService_waitForStart_args');
  if (this.gameId) {
    output.writeFieldBegin('gameId', Thrift.Type.I32, 1);
    output.writeI32(this.gameId);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BombahService_waitForStart_result = function(args) {
  this.gameOverException = null;
  if (args) {
    if (args.gameOverException !== undefined) {
      this.gameOverException = args.gameOverException;
    }
  }
};
BombahService_waitForStart_result.prototype = {};
BombahService_waitForStart_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.gameOverException = new ttypes.GameOverException();
        this.gameOverException.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BombahService_waitForStart_result.prototype.write = function(output) {
  output.writeStructBegin('BombahService_waitForStart_result');
  if (this.gameOverException) {
    output.writeFieldBegin('gameOverException', Thrift.Type.STRUCT, 1);
    this.gameOverException.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BombahService_getMapState_args = function(args) {
  this.gameId = null;
  if (args) {
    if (args.gameId !== undefined) {
      this.gameId = args.gameId;
    }
  }
};
BombahService_getMapState_args.prototype = {};
BombahService_getMapState_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.I32) {
        this.gameId = input.readI32();
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BombahService_getMapState_args.prototype.write = function(output) {
  output.writeStructBegin('BombahService_getMapState_args');
  if (this.gameId) {
    output.writeFieldBegin('gameId', Thrift.Type.I32, 1);
    output.writeI32(this.gameId);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BombahService_getMapState_result = function(args) {
  this.success = null;
  this.gameOver = null;
  if (args) {
    if (args.success !== undefined) {
      this.success = args.success;
    }
    if (args.gameOver !== undefined) {
      this.gameOver = args.gameOver;
    }
  }
};
BombahService_getMapState_result.prototype = {};
BombahService_getMapState_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.MapState();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.gameOver = new ttypes.GameOverException();
        this.gameOver.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

BombahService_getMapState_result.prototype.write = function(output) {
  output.writeStructBegin('BombahService_getMapState_result');
  if (this.success) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  if (this.gameOver) {
    output.writeFieldBegin('gameOver', Thrift.Type.STRUCT, 1);
    this.gameOver.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var BombahServiceClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this.seqid = 0;
    this._reqs = {};
};
BombahServiceClient.prototype = {};
BombahServiceClient.prototype.ping = function(callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_ping();
};

BombahServiceClient.prototype.send_ping = function() {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('ping', Thrift.MessageType.CALL, this.seqid);
  var args = new BombahService_ping_args();
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

BombahServiceClient.prototype.recv_ping = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new BombahService_ping_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('ping failed: unknown result');
};
BombahServiceClient.prototype.controllerEvent = function(playerId, controllerState, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_controllerEvent(playerId, controllerState);
};

BombahServiceClient.prototype.send_controllerEvent = function(playerId, controllerState) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('controllerEvent', Thrift.MessageType.CALL, this.seqid);
  var args = new BombahService_controllerEvent_args();
  args.playerId = playerId;
  args.controllerState = controllerState;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

BombahServiceClient.prototype.recv_controllerEvent = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new BombahService_controllerEvent_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.youAreDead) {
    return callback(result.youAreDead);
  }
  if (null !== result.gameOver) {
    return callback(result.gameOver);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('controllerEvent failed: unknown result');
};
BombahServiceClient.prototype.move = function(playerId, moveAction, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_move(playerId, moveAction);
};

BombahServiceClient.prototype.send_move = function(playerId, moveAction) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('move', Thrift.MessageType.CALL, this.seqid);
  var args = new BombahService_move_args();
  args.playerId = playerId;
  args.moveAction = moveAction;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

BombahServiceClient.prototype.recv_move = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new BombahService_move_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.youAreDead) {
    return callback(result.youAreDead);
  }
  if (null !== result.gameOver) {
    return callback(result.gameOver);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('move failed: unknown result');
};
BombahServiceClient.prototype.bomb = function(playerId, bombAction, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_bomb(playerId, bombAction);
};

BombahServiceClient.prototype.send_bomb = function(playerId, bombAction) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('bomb', Thrift.MessageType.CALL, this.seqid);
  var args = new BombahService_bomb_args();
  args.playerId = playerId;
  args.bombAction = bombAction;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

BombahServiceClient.prototype.recv_bomb = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new BombahService_bomb_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.youAreDead) {
    return callback(result.youAreDead);
  }
  if (null !== result.gameOver) {
    return callback(result.gameOver);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('bomb failed: unknown result');
};
BombahServiceClient.prototype.waitTicks = function(gameId, ticks, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_waitTicks(gameId, ticks);
};

BombahServiceClient.prototype.send_waitTicks = function(gameId, ticks) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('waitTicks', Thrift.MessageType.CALL, this.seqid);
  var args = new BombahService_waitTicks_args();
  args.gameId = gameId;
  args.ticks = ticks;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

BombahServiceClient.prototype.recv_waitTicks = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new BombahService_waitTicks_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.youAreDead) {
    return callback(result.youAreDead);
  }
  if (null !== result.gameOver) {
    return callback(result.gameOver);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('waitTicks failed: unknown result');
};
BombahServiceClient.prototype.waitForTick = function(gameId, tick, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_waitForTick(gameId, tick);
};

BombahServiceClient.prototype.send_waitForTick = function(gameId, tick) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('waitForTick', Thrift.MessageType.CALL, this.seqid);
  var args = new BombahService_waitForTick_args();
  args.gameId = gameId;
  args.tick = tick;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

BombahServiceClient.prototype.recv_waitForTick = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new BombahService_waitForTick_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.youAreDead) {
    return callback(result.youAreDead);
  }
  if (null !== result.gameOver) {
    return callback(result.gameOver);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('waitForTick failed: unknown result');
};
BombahServiceClient.prototype.joinGame = function(gameId, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_joinGame(gameId);
};

BombahServiceClient.prototype.send_joinGame = function(gameId) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('joinGame', Thrift.MessageType.CALL, this.seqid);
  var args = new BombahService_joinGame_args();
  args.gameId = gameId;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

BombahServiceClient.prototype.recv_joinGame = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new BombahService_joinGame_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.gameOverException) {
    return callback(result.gameOverException);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('joinGame failed: unknown result');
};
BombahServiceClient.prototype.getGameInfo = function(gameId, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_getGameInfo(gameId);
};

BombahServiceClient.prototype.send_getGameInfo = function(gameId) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getGameInfo', Thrift.MessageType.CALL, this.seqid);
  var args = new BombahService_getGameInfo_args();
  args.gameId = gameId;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

BombahServiceClient.prototype.recv_getGameInfo = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new BombahService_getGameInfo_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.gameOverException) {
    return callback(result.gameOverException);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getGameInfo failed: unknown result');
};
BombahServiceClient.prototype.debugResetGame = function(gameId, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_debugResetGame(gameId);
};

BombahServiceClient.prototype.send_debugResetGame = function(gameId) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('debugResetGame', Thrift.MessageType.CALL, this.seqid);
  var args = new BombahService_debugResetGame_args();
  args.gameId = gameId;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

BombahServiceClient.prototype.recv_debugResetGame = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new BombahService_debugResetGame_result();
  result.read(input);
  input.readMessageEnd();

  callback(null)
};
BombahServiceClient.prototype.waitForStart = function(gameId, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_waitForStart(gameId);
};

BombahServiceClient.prototype.send_waitForStart = function(gameId) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('waitForStart', Thrift.MessageType.CALL, this.seqid);
  var args = new BombahService_waitForStart_args();
  args.gameId = gameId;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

BombahServiceClient.prototype.recv_waitForStart = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new BombahService_waitForStart_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.gameOverException) {
    return callback(result.gameOverException);
  }
  callback(null)
};
BombahServiceClient.prototype.getMapState = function(gameId, callback) {
  this.seqid += 1;
  this._reqs[this.seqid] = callback;
  this.send_getMapState(gameId);
};

BombahServiceClient.prototype.send_getMapState = function(gameId) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('getMapState', Thrift.MessageType.CALL, this.seqid);
  var args = new BombahService_getMapState_args();
  args.gameId = gameId;
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

BombahServiceClient.prototype.recv_getMapState = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new BombahService_getMapState_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.gameOver) {
    return callback(result.gameOver);
  }
  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('getMapState failed: unknown result');
};
var BombahServiceProcessor = exports.Processor = function(handler) {
  this._handler = handler
}
BombahServiceProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.Exception, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}

BombahServiceProcessor.prototype.process_ping = function(seqid, input, output) {
  var args = new BombahService_ping_args();
  args.read(input);
  input.readMessageEnd();
  var result = new BombahService_ping_result();
  this._handler.ping(function (success) {
    result.success = success;
    output.writeMessageBegin("ping", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

BombahServiceProcessor.prototype.process_controllerEvent = function(seqid, input, output) {
  var args = new BombahService_controllerEvent_args();
  args.read(input);
  input.readMessageEnd();
  var result = new BombahService_controllerEvent_result();
  this._handler.controllerEvent(args.playerId, args.controllerState, function (success) {
    result.success = success;
    output.writeMessageBegin("controllerEvent", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

BombahServiceProcessor.prototype.process_move = function(seqid, input, output) {
  var args = new BombahService_move_args();
  args.read(input);
  input.readMessageEnd();
  var result = new BombahService_move_result();
  this._handler.move(args.playerId, args.moveAction, function (success) {
    result.success = success;
    output.writeMessageBegin("move", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

BombahServiceProcessor.prototype.process_bomb = function(seqid, input, output) {
  var args = new BombahService_bomb_args();
  args.read(input);
  input.readMessageEnd();
  var result = new BombahService_bomb_result();
  this._handler.bomb(args.playerId, args.bombAction, function (success) {
    result.success = success;
    output.writeMessageBegin("bomb", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

BombahServiceProcessor.prototype.process_waitTicks = function(seqid, input, output) {
  var args = new BombahService_waitTicks_args();
  args.read(input);
  input.readMessageEnd();
  var result = new BombahService_waitTicks_result();
  this._handler.waitTicks(args.gameId, args.ticks, function (success) {
    result.success = success;
    output.writeMessageBegin("waitTicks", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

BombahServiceProcessor.prototype.process_waitForTick = function(seqid, input, output) {
  var args = new BombahService_waitForTick_args();
  args.read(input);
  input.readMessageEnd();
  var result = new BombahService_waitForTick_result();
  this._handler.waitForTick(args.gameId, args.tick, function (success) {
    result.success = success;
    output.writeMessageBegin("waitForTick", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

BombahServiceProcessor.prototype.process_joinGame = function(seqid, input, output) {
  var args = new BombahService_joinGame_args();
  args.read(input);
  input.readMessageEnd();
  var result = new BombahService_joinGame_result();
  this._handler.joinGame(args.gameId, function (success) {
    result.success = success;
    output.writeMessageBegin("joinGame", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

BombahServiceProcessor.prototype.process_getGameInfo = function(seqid, input, output) {
  var args = new BombahService_getGameInfo_args();
  args.read(input);
  input.readMessageEnd();
  var result = new BombahService_getGameInfo_result();
  this._handler.getGameInfo(args.gameId, function (success) {
    result.success = success;
    output.writeMessageBegin("getGameInfo", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

BombahServiceProcessor.prototype.process_debugResetGame = function(seqid, input, output) {
  var args = new BombahService_debugResetGame_args();
  args.read(input);
  input.readMessageEnd();
  var result = new BombahService_debugResetGame_result();
  this._handler.debugResetGame(args.gameId, function (success) {
    result.success = success;
    output.writeMessageBegin("debugResetGame", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

BombahServiceProcessor.prototype.process_waitForStart = function(seqid, input, output) {
  var args = new BombahService_waitForStart_args();
  args.read(input);
  input.readMessageEnd();
  var result = new BombahService_waitForStart_result();
  this._handler.waitForStart(args.gameId, function (success) {
    result.success = success;
    output.writeMessageBegin("waitForStart", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

BombahServiceProcessor.prototype.process_getMapState = function(seqid, input, output) {
  var args = new BombahService_getMapState_args();
  args.read(input);
  input.readMessageEnd();
  var result = new BombahService_getMapState_result();
  this._handler.getMapState(args.gameId, function (success) {
    result.success = success;
    output.writeMessageBegin("getMapState", Thrift.MessageType.REPLY, seqid);
    result.write(output);
    output.writeMessageEnd();
    output.flush();
  })
}

