/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.riksa.bombah.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class MapState implements org.apache.thrift.TBase<MapState, MapState._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("MapState");

  private static final org.apache.thrift.protocol.TField INDESTRUCTIBLE_TILES_FIELD_DESC = new org.apache.thrift.protocol.TField("indestructibleTiles", org.apache.thrift.protocol.TType.SET, (short)1);
  private static final org.apache.thrift.protocol.TField DESTRUCTIBLE_TILES_FIELD_DESC = new org.apache.thrift.protocol.TField("destructibleTiles", org.apache.thrift.protocol.TType.SET, (short)2);
  private static final org.apache.thrift.protocol.TField BOMBS_FIELD_DESC = new org.apache.thrift.protocol.TField("bombs", org.apache.thrift.protocol.TType.SET, (short)3);
  private static final org.apache.thrift.protocol.TField PLAYERS_FIELD_DESC = new org.apache.thrift.protocol.TField("players", org.apache.thrift.protocol.TType.LIST, (short)4);
  private static final org.apache.thrift.protocol.TField TICKS_REMAINING_FIELD_DESC = new org.apache.thrift.protocol.TField("ticksRemaining", org.apache.thrift.protocol.TType.I32, (short)5);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new MapStateStandardSchemeFactory());
    schemes.put(TupleScheme.class, new MapStateTupleSchemeFactory());
  }

  public Set<TileState> indestructibleTiles; // required
  public Set<TileState> destructibleTiles; // required
  public Set<BombState> bombs; // required
  public List<PlayerState> players; // required
  public int ticksRemaining; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    INDESTRUCTIBLE_TILES((short)1, "indestructibleTiles"),
    DESTRUCTIBLE_TILES((short)2, "destructibleTiles"),
    BOMBS((short)3, "bombs"),
    PLAYERS((short)4, "players"),
    TICKS_REMAINING((short)5, "ticksRemaining");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // INDESTRUCTIBLE_TILES
          return INDESTRUCTIBLE_TILES;
        case 2: // DESTRUCTIBLE_TILES
          return DESTRUCTIBLE_TILES;
        case 3: // BOMBS
          return BOMBS;
        case 4: // PLAYERS
          return PLAYERS;
        case 5: // TICKS_REMAINING
          return TICKS_REMAINING;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __TICKSREMAINING_ISSET_ID = 0;
  private BitSet __isset_bit_vector = new BitSet(1);
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.INDESTRUCTIBLE_TILES, new org.apache.thrift.meta_data.FieldMetaData("indestructibleTiles", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.SetMetaData(org.apache.thrift.protocol.TType.SET, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TileState.class))));
    tmpMap.put(_Fields.DESTRUCTIBLE_TILES, new org.apache.thrift.meta_data.FieldMetaData("destructibleTiles", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.SetMetaData(org.apache.thrift.protocol.TType.SET, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TileState.class))));
    tmpMap.put(_Fields.BOMBS, new org.apache.thrift.meta_data.FieldMetaData("bombs", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.SetMetaData(org.apache.thrift.protocol.TType.SET, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, BombState.class))));
    tmpMap.put(_Fields.PLAYERS, new org.apache.thrift.meta_data.FieldMetaData("players", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, PlayerState.class))));
    tmpMap.put(_Fields.TICKS_REMAINING, new org.apache.thrift.meta_data.FieldMetaData("ticksRemaining", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(MapState.class, metaDataMap);
  }

  public MapState() {
  }

  public MapState(
    Set<TileState> indestructibleTiles,
    Set<TileState> destructibleTiles,
    Set<BombState> bombs,
    List<PlayerState> players,
    int ticksRemaining)
  {
    this();
    this.indestructibleTiles = indestructibleTiles;
    this.destructibleTiles = destructibleTiles;
    this.bombs = bombs;
    this.players = players;
    this.ticksRemaining = ticksRemaining;
    setTicksRemainingIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public MapState(MapState other) {
    __isset_bit_vector.clear();
    __isset_bit_vector.or(other.__isset_bit_vector);
    if (other.isSetIndestructibleTiles()) {
      Set<TileState> __this__indestructibleTiles = new HashSet<TileState>();
      for (TileState other_element : other.indestructibleTiles) {
        __this__indestructibleTiles.add(new TileState(other_element));
      }
      this.indestructibleTiles = __this__indestructibleTiles;
    }
    if (other.isSetDestructibleTiles()) {
      Set<TileState> __this__destructibleTiles = new HashSet<TileState>();
      for (TileState other_element : other.destructibleTiles) {
        __this__destructibleTiles.add(new TileState(other_element));
      }
      this.destructibleTiles = __this__destructibleTiles;
    }
    if (other.isSetBombs()) {
      Set<BombState> __this__bombs = new HashSet<BombState>();
      for (BombState other_element : other.bombs) {
        __this__bombs.add(new BombState(other_element));
      }
      this.bombs = __this__bombs;
    }
    if (other.isSetPlayers()) {
      List<PlayerState> __this__players = new ArrayList<PlayerState>();
      for (PlayerState other_element : other.players) {
        __this__players.add(new PlayerState(other_element));
      }
      this.players = __this__players;
    }
    this.ticksRemaining = other.ticksRemaining;
  }

  public MapState deepCopy() {
    return new MapState(this);
  }

  @Override
  public void clear() {
    this.indestructibleTiles = null;
    this.destructibleTiles = null;
    this.bombs = null;
    this.players = null;
    setTicksRemainingIsSet(false);
    this.ticksRemaining = 0;
  }

  public int getIndestructibleTilesSize() {
    return (this.indestructibleTiles == null) ? 0 : this.indestructibleTiles.size();
  }

  public java.util.Iterator<TileState> getIndestructibleTilesIterator() {
    return (this.indestructibleTiles == null) ? null : this.indestructibleTiles.iterator();
  }

  public void addToIndestructibleTiles(TileState elem) {
    if (this.indestructibleTiles == null) {
      this.indestructibleTiles = new HashSet<TileState>();
    }
    this.indestructibleTiles.add(elem);
  }

  public Set<TileState> getIndestructibleTiles() {
    return this.indestructibleTiles;
  }

  public MapState setIndestructibleTiles(Set<TileState> indestructibleTiles) {
    this.indestructibleTiles = indestructibleTiles;
    return this;
  }

  public void unsetIndestructibleTiles() {
    this.indestructibleTiles = null;
  }

  /** Returns true if field indestructibleTiles is set (has been assigned a value) and false otherwise */
  public boolean isSetIndestructibleTiles() {
    return this.indestructibleTiles != null;
  }

  public void setIndestructibleTilesIsSet(boolean value) {
    if (!value) {
      this.indestructibleTiles = null;
    }
  }

  public int getDestructibleTilesSize() {
    return (this.destructibleTiles == null) ? 0 : this.destructibleTiles.size();
  }

  public java.util.Iterator<TileState> getDestructibleTilesIterator() {
    return (this.destructibleTiles == null) ? null : this.destructibleTiles.iterator();
  }

  public void addToDestructibleTiles(TileState elem) {
    if (this.destructibleTiles == null) {
      this.destructibleTiles = new HashSet<TileState>();
    }
    this.destructibleTiles.add(elem);
  }

  public Set<TileState> getDestructibleTiles() {
    return this.destructibleTiles;
  }

  public MapState setDestructibleTiles(Set<TileState> destructibleTiles) {
    this.destructibleTiles = destructibleTiles;
    return this;
  }

  public void unsetDestructibleTiles() {
    this.destructibleTiles = null;
  }

  /** Returns true if field destructibleTiles is set (has been assigned a value) and false otherwise */
  public boolean isSetDestructibleTiles() {
    return this.destructibleTiles != null;
  }

  public void setDestructibleTilesIsSet(boolean value) {
    if (!value) {
      this.destructibleTiles = null;
    }
  }

  public int getBombsSize() {
    return (this.bombs == null) ? 0 : this.bombs.size();
  }

  public java.util.Iterator<BombState> getBombsIterator() {
    return (this.bombs == null) ? null : this.bombs.iterator();
  }

  public void addToBombs(BombState elem) {
    if (this.bombs == null) {
      this.bombs = new HashSet<BombState>();
    }
    this.bombs.add(elem);
  }

  public Set<BombState> getBombs() {
    return this.bombs;
  }

  public MapState setBombs(Set<BombState> bombs) {
    this.bombs = bombs;
    return this;
  }

  public void unsetBombs() {
    this.bombs = null;
  }

  /** Returns true if field bombs is set (has been assigned a value) and false otherwise */
  public boolean isSetBombs() {
    return this.bombs != null;
  }

  public void setBombsIsSet(boolean value) {
    if (!value) {
      this.bombs = null;
    }
  }

  public int getPlayersSize() {
    return (this.players == null) ? 0 : this.players.size();
  }

  public java.util.Iterator<PlayerState> getPlayersIterator() {
    return (this.players == null) ? null : this.players.iterator();
  }

  public void addToPlayers(PlayerState elem) {
    if (this.players == null) {
      this.players = new ArrayList<PlayerState>();
    }
    this.players.add(elem);
  }

  public List<PlayerState> getPlayers() {
    return this.players;
  }

  public MapState setPlayers(List<PlayerState> players) {
    this.players = players;
    return this;
  }

  public void unsetPlayers() {
    this.players = null;
  }

  /** Returns true if field players is set (has been assigned a value) and false otherwise */
  public boolean isSetPlayers() {
    return this.players != null;
  }

  public void setPlayersIsSet(boolean value) {
    if (!value) {
      this.players = null;
    }
  }

  public int getTicksRemaining() {
    return this.ticksRemaining;
  }

  public MapState setTicksRemaining(int ticksRemaining) {
    this.ticksRemaining = ticksRemaining;
    setTicksRemainingIsSet(true);
    return this;
  }

  public void unsetTicksRemaining() {
    __isset_bit_vector.clear(__TICKSREMAINING_ISSET_ID);
  }

  /** Returns true if field ticksRemaining is set (has been assigned a value) and false otherwise */
  public boolean isSetTicksRemaining() {
    return __isset_bit_vector.get(__TICKSREMAINING_ISSET_ID);
  }

  public void setTicksRemainingIsSet(boolean value) {
    __isset_bit_vector.set(__TICKSREMAINING_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case INDESTRUCTIBLE_TILES:
      if (value == null) {
        unsetIndestructibleTiles();
      } else {
        setIndestructibleTiles((Set<TileState>)value);
      }
      break;

    case DESTRUCTIBLE_TILES:
      if (value == null) {
        unsetDestructibleTiles();
      } else {
        setDestructibleTiles((Set<TileState>)value);
      }
      break;

    case BOMBS:
      if (value == null) {
        unsetBombs();
      } else {
        setBombs((Set<BombState>)value);
      }
      break;

    case PLAYERS:
      if (value == null) {
        unsetPlayers();
      } else {
        setPlayers((List<PlayerState>)value);
      }
      break;

    case TICKS_REMAINING:
      if (value == null) {
        unsetTicksRemaining();
      } else {
        setTicksRemaining((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case INDESTRUCTIBLE_TILES:
      return getIndestructibleTiles();

    case DESTRUCTIBLE_TILES:
      return getDestructibleTiles();

    case BOMBS:
      return getBombs();

    case PLAYERS:
      return getPlayers();

    case TICKS_REMAINING:
      return Integer.valueOf(getTicksRemaining());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case INDESTRUCTIBLE_TILES:
      return isSetIndestructibleTiles();
    case DESTRUCTIBLE_TILES:
      return isSetDestructibleTiles();
    case BOMBS:
      return isSetBombs();
    case PLAYERS:
      return isSetPlayers();
    case TICKS_REMAINING:
      return isSetTicksRemaining();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof MapState)
      return this.equals((MapState)that);
    return false;
  }

  public boolean equals(MapState that) {
    if (that == null)
      return false;

    boolean this_present_indestructibleTiles = true && this.isSetIndestructibleTiles();
    boolean that_present_indestructibleTiles = true && that.isSetIndestructibleTiles();
    if (this_present_indestructibleTiles || that_present_indestructibleTiles) {
      if (!(this_present_indestructibleTiles && that_present_indestructibleTiles))
        return false;
      if (!this.indestructibleTiles.equals(that.indestructibleTiles))
        return false;
    }

    boolean this_present_destructibleTiles = true && this.isSetDestructibleTiles();
    boolean that_present_destructibleTiles = true && that.isSetDestructibleTiles();
    if (this_present_destructibleTiles || that_present_destructibleTiles) {
      if (!(this_present_destructibleTiles && that_present_destructibleTiles))
        return false;
      if (!this.destructibleTiles.equals(that.destructibleTiles))
        return false;
    }

    boolean this_present_bombs = true && this.isSetBombs();
    boolean that_present_bombs = true && that.isSetBombs();
    if (this_present_bombs || that_present_bombs) {
      if (!(this_present_bombs && that_present_bombs))
        return false;
      if (!this.bombs.equals(that.bombs))
        return false;
    }

    boolean this_present_players = true && this.isSetPlayers();
    boolean that_present_players = true && that.isSetPlayers();
    if (this_present_players || that_present_players) {
      if (!(this_present_players && that_present_players))
        return false;
      if (!this.players.equals(that.players))
        return false;
    }

    boolean this_present_ticksRemaining = true;
    boolean that_present_ticksRemaining = true;
    if (this_present_ticksRemaining || that_present_ticksRemaining) {
      if (!(this_present_ticksRemaining && that_present_ticksRemaining))
        return false;
      if (this.ticksRemaining != that.ticksRemaining)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(MapState other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    MapState typedOther = (MapState)other;

    lastComparison = Boolean.valueOf(isSetIndestructibleTiles()).compareTo(typedOther.isSetIndestructibleTiles());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIndestructibleTiles()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.indestructibleTiles, typedOther.indestructibleTiles);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDestructibleTiles()).compareTo(typedOther.isSetDestructibleTiles());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDestructibleTiles()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.destructibleTiles, typedOther.destructibleTiles);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetBombs()).compareTo(typedOther.isSetBombs());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBombs()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.bombs, typedOther.bombs);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPlayers()).compareTo(typedOther.isSetPlayers());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPlayers()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.players, typedOther.players);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTicksRemaining()).compareTo(typedOther.isSetTicksRemaining());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTicksRemaining()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ticksRemaining, typedOther.ticksRemaining);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("MapState(");
    boolean first = true;

    sb.append("indestructibleTiles:");
    if (this.indestructibleTiles == null) {
      sb.append("null");
    } else {
      sb.append(this.indestructibleTiles);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("destructibleTiles:");
    if (this.destructibleTiles == null) {
      sb.append("null");
    } else {
      sb.append(this.destructibleTiles);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("bombs:");
    if (this.bombs == null) {
      sb.append("null");
    } else {
      sb.append(this.bombs);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("players:");
    if (this.players == null) {
      sb.append("null");
    } else {
      sb.append(this.players);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("ticksRemaining:");
    sb.append(this.ticksRemaining);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bit_vector = new BitSet(1);
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class MapStateStandardSchemeFactory implements SchemeFactory {
    public MapStateStandardScheme getScheme() {
      return new MapStateStandardScheme();
    }
  }

  private static class MapStateStandardScheme extends StandardScheme<MapState> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, MapState struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // INDESTRUCTIBLE_TILES
            if (schemeField.type == org.apache.thrift.protocol.TType.SET) {
              {
                org.apache.thrift.protocol.TSet _set0 = iprot.readSetBegin();
                struct.indestructibleTiles = new HashSet<TileState>(2*_set0.size);
                for (int _i1 = 0; _i1 < _set0.size; ++_i1)
                {
                  TileState _elem2; // required
                  _elem2 = new TileState();
                  _elem2.read(iprot);
                  struct.indestructibleTiles.add(_elem2);
                }
                iprot.readSetEnd();
              }
              struct.setIndestructibleTilesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // DESTRUCTIBLE_TILES
            if (schemeField.type == org.apache.thrift.protocol.TType.SET) {
              {
                org.apache.thrift.protocol.TSet _set3 = iprot.readSetBegin();
                struct.destructibleTiles = new HashSet<TileState>(2*_set3.size);
                for (int _i4 = 0; _i4 < _set3.size; ++_i4)
                {
                  TileState _elem5; // required
                  _elem5 = new TileState();
                  _elem5.read(iprot);
                  struct.destructibleTiles.add(_elem5);
                }
                iprot.readSetEnd();
              }
              struct.setDestructibleTilesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // BOMBS
            if (schemeField.type == org.apache.thrift.protocol.TType.SET) {
              {
                org.apache.thrift.protocol.TSet _set6 = iprot.readSetBegin();
                struct.bombs = new HashSet<BombState>(2*_set6.size);
                for (int _i7 = 0; _i7 < _set6.size; ++_i7)
                {
                  BombState _elem8; // required
                  _elem8 = new BombState();
                  _elem8.read(iprot);
                  struct.bombs.add(_elem8);
                }
                iprot.readSetEnd();
              }
              struct.setBombsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // PLAYERS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list9 = iprot.readListBegin();
                struct.players = new ArrayList<PlayerState>(_list9.size);
                for (int _i10 = 0; _i10 < _list9.size; ++_i10)
                {
                  PlayerState _elem11; // required
                  _elem11 = new PlayerState();
                  _elem11.read(iprot);
                  struct.players.add(_elem11);
                }
                iprot.readListEnd();
              }
              struct.setPlayersIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // TICKS_REMAINING
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.ticksRemaining = iprot.readI32();
              struct.setTicksRemainingIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, MapState struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.indestructibleTiles != null) {
        oprot.writeFieldBegin(INDESTRUCTIBLE_TILES_FIELD_DESC);
        {
          oprot.writeSetBegin(new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.STRUCT, struct.indestructibleTiles.size()));
          for (TileState _iter12 : struct.indestructibleTiles)
          {
            _iter12.write(oprot);
          }
          oprot.writeSetEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.destructibleTiles != null) {
        oprot.writeFieldBegin(DESTRUCTIBLE_TILES_FIELD_DESC);
        {
          oprot.writeSetBegin(new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.STRUCT, struct.destructibleTiles.size()));
          for (TileState _iter13 : struct.destructibleTiles)
          {
            _iter13.write(oprot);
          }
          oprot.writeSetEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.bombs != null) {
        oprot.writeFieldBegin(BOMBS_FIELD_DESC);
        {
          oprot.writeSetBegin(new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.STRUCT, struct.bombs.size()));
          for (BombState _iter14 : struct.bombs)
          {
            _iter14.write(oprot);
          }
          oprot.writeSetEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.players != null) {
        oprot.writeFieldBegin(PLAYERS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.players.size()));
          for (PlayerState _iter15 : struct.players)
          {
            _iter15.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(TICKS_REMAINING_FIELD_DESC);
      oprot.writeI32(struct.ticksRemaining);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class MapStateTupleSchemeFactory implements SchemeFactory {
    public MapStateTupleScheme getScheme() {
      return new MapStateTupleScheme();
    }
  }

  private static class MapStateTupleScheme extends TupleScheme<MapState> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, MapState struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetIndestructibleTiles()) {
        optionals.set(0);
      }
      if (struct.isSetDestructibleTiles()) {
        optionals.set(1);
      }
      if (struct.isSetBombs()) {
        optionals.set(2);
      }
      if (struct.isSetPlayers()) {
        optionals.set(3);
      }
      if (struct.isSetTicksRemaining()) {
        optionals.set(4);
      }
      oprot.writeBitSet(optionals, 5);
      if (struct.isSetIndestructibleTiles()) {
        {
          oprot.writeI32(struct.indestructibleTiles.size());
          for (TileState _iter16 : struct.indestructibleTiles)
          {
            _iter16.write(oprot);
          }
        }
      }
      if (struct.isSetDestructibleTiles()) {
        {
          oprot.writeI32(struct.destructibleTiles.size());
          for (TileState _iter17 : struct.destructibleTiles)
          {
            _iter17.write(oprot);
          }
        }
      }
      if (struct.isSetBombs()) {
        {
          oprot.writeI32(struct.bombs.size());
          for (BombState _iter18 : struct.bombs)
          {
            _iter18.write(oprot);
          }
        }
      }
      if (struct.isSetPlayers()) {
        {
          oprot.writeI32(struct.players.size());
          for (PlayerState _iter19 : struct.players)
          {
            _iter19.write(oprot);
          }
        }
      }
      if (struct.isSetTicksRemaining()) {
        oprot.writeI32(struct.ticksRemaining);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, MapState struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(5);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TSet _set20 = new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.indestructibleTiles = new HashSet<TileState>(2*_set20.size);
          for (int _i21 = 0; _i21 < _set20.size; ++_i21)
          {
            TileState _elem22; // required
            _elem22 = new TileState();
            _elem22.read(iprot);
            struct.indestructibleTiles.add(_elem22);
          }
        }
        struct.setIndestructibleTilesIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TSet _set23 = new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.destructibleTiles = new HashSet<TileState>(2*_set23.size);
          for (int _i24 = 0; _i24 < _set23.size; ++_i24)
          {
            TileState _elem25; // required
            _elem25 = new TileState();
            _elem25.read(iprot);
            struct.destructibleTiles.add(_elem25);
          }
        }
        struct.setDestructibleTilesIsSet(true);
      }
      if (incoming.get(2)) {
        {
          org.apache.thrift.protocol.TSet _set26 = new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.bombs = new HashSet<BombState>(2*_set26.size);
          for (int _i27 = 0; _i27 < _set26.size; ++_i27)
          {
            BombState _elem28; // required
            _elem28 = new BombState();
            _elem28.read(iprot);
            struct.bombs.add(_elem28);
          }
        }
        struct.setBombsIsSet(true);
      }
      if (incoming.get(3)) {
        {
          org.apache.thrift.protocol.TList _list29 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.players = new ArrayList<PlayerState>(_list29.size);
          for (int _i30 = 0; _i30 < _list29.size; ++_i30)
          {
            PlayerState _elem31; // required
            _elem31 = new PlayerState();
            _elem31.read(iprot);
            struct.players.add(_elem31);
          }
        }
        struct.setPlayersIsSet(true);
      }
      if (incoming.get(4)) {
        struct.ticksRemaining = iprot.readI32();
        struct.setTicksRemainingIsSet(true);
      }
    }
  }

}

