/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.riksa.bombah.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class TileState implements org.apache.thrift.TBase<TileState, TileState._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TileState");

  private static final org.apache.thrift.protocol.TField TILE_FIELD_DESC = new org.apache.thrift.protocol.TField("tile", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField X_COORDINATE_FIELD_DESC = new org.apache.thrift.protocol.TField("xCoordinate", org.apache.thrift.protocol.TType.BYTE, (short)2);
  private static final org.apache.thrift.protocol.TField Y_COORDINATE_FIELD_DESC = new org.apache.thrift.protocol.TField("yCoordinate", org.apache.thrift.protocol.TType.BYTE, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new TileStateStandardSchemeFactory());
    schemes.put(TupleScheme.class, new TileStateTupleSchemeFactory());
  }

  /**
   * 
   * @see Tile
   */
  public Tile tile; // required
  public byte xCoordinate; // required
  public byte yCoordinate; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 
     * @see Tile
     */
    TILE((short)1, "tile"),
    X_COORDINATE((short)2, "xCoordinate"),
    Y_COORDINATE((short)3, "yCoordinate");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TILE
          return TILE;
        case 2: // X_COORDINATE
          return X_COORDINATE;
        case 3: // Y_COORDINATE
          return Y_COORDINATE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __XCOORDINATE_ISSET_ID = 0;
  private static final int __YCOORDINATE_ISSET_ID = 1;
  private BitSet __isset_bit_vector = new BitSet(2);
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TILE, new org.apache.thrift.meta_data.FieldMetaData("tile", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, Tile.class)));
    tmpMap.put(_Fields.X_COORDINATE, new org.apache.thrift.meta_data.FieldMetaData("xCoordinate", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BYTE)));
    tmpMap.put(_Fields.Y_COORDINATE, new org.apache.thrift.meta_data.FieldMetaData("yCoordinate", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BYTE)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TileState.class, metaDataMap);
  }

  public TileState() {
  }

  public TileState(
    Tile tile,
    byte xCoordinate,
    byte yCoordinate)
  {
    this();
    this.tile = tile;
    this.xCoordinate = xCoordinate;
    setXCoordinateIsSet(true);
    this.yCoordinate = yCoordinate;
    setYCoordinateIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TileState(TileState other) {
    __isset_bit_vector.clear();
    __isset_bit_vector.or(other.__isset_bit_vector);
    if (other.isSetTile()) {
      this.tile = other.tile;
    }
    this.xCoordinate = other.xCoordinate;
    this.yCoordinate = other.yCoordinate;
  }

  public TileState deepCopy() {
    return new TileState(this);
  }

  @Override
  public void clear() {
    this.tile = null;
    setXCoordinateIsSet(false);
    this.xCoordinate = 0;
    setYCoordinateIsSet(false);
    this.yCoordinate = 0;
  }

  /**
   * 
   * @see Tile
   */
  public Tile getTile() {
    return this.tile;
  }

  /**
   * 
   * @see Tile
   */
  public TileState setTile(Tile tile) {
    this.tile = tile;
    return this;
  }

  public void unsetTile() {
    this.tile = null;
  }

  /** Returns true if field tile is set (has been assigned a value) and false otherwise */
  public boolean isSetTile() {
    return this.tile != null;
  }

  public void setTileIsSet(boolean value) {
    if (!value) {
      this.tile = null;
    }
  }

  public byte getXCoordinate() {
    return this.xCoordinate;
  }

  public TileState setXCoordinate(byte xCoordinate) {
    this.xCoordinate = xCoordinate;
    setXCoordinateIsSet(true);
    return this;
  }

  public void unsetXCoordinate() {
    __isset_bit_vector.clear(__XCOORDINATE_ISSET_ID);
  }

  /** Returns true if field xCoordinate is set (has been assigned a value) and false otherwise */
  public boolean isSetXCoordinate() {
    return __isset_bit_vector.get(__XCOORDINATE_ISSET_ID);
  }

  public void setXCoordinateIsSet(boolean value) {
    __isset_bit_vector.set(__XCOORDINATE_ISSET_ID, value);
  }

  public byte getYCoordinate() {
    return this.yCoordinate;
  }

  public TileState setYCoordinate(byte yCoordinate) {
    this.yCoordinate = yCoordinate;
    setYCoordinateIsSet(true);
    return this;
  }

  public void unsetYCoordinate() {
    __isset_bit_vector.clear(__YCOORDINATE_ISSET_ID);
  }

  /** Returns true if field yCoordinate is set (has been assigned a value) and false otherwise */
  public boolean isSetYCoordinate() {
    return __isset_bit_vector.get(__YCOORDINATE_ISSET_ID);
  }

  public void setYCoordinateIsSet(boolean value) {
    __isset_bit_vector.set(__YCOORDINATE_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case TILE:
      if (value == null) {
        unsetTile();
      } else {
        setTile((Tile)value);
      }
      break;

    case X_COORDINATE:
      if (value == null) {
        unsetXCoordinate();
      } else {
        setXCoordinate((Byte)value);
      }
      break;

    case Y_COORDINATE:
      if (value == null) {
        unsetYCoordinate();
      } else {
        setYCoordinate((Byte)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case TILE:
      return getTile();

    case X_COORDINATE:
      return Byte.valueOf(getXCoordinate());

    case Y_COORDINATE:
      return Byte.valueOf(getYCoordinate());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case TILE:
      return isSetTile();
    case X_COORDINATE:
      return isSetXCoordinate();
    case Y_COORDINATE:
      return isSetYCoordinate();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof TileState)
      return this.equals((TileState)that);
    return false;
  }

  public boolean equals(TileState that) {
    if (that == null)
      return false;

    boolean this_present_tile = true && this.isSetTile();
    boolean that_present_tile = true && that.isSetTile();
    if (this_present_tile || that_present_tile) {
      if (!(this_present_tile && that_present_tile))
        return false;
      if (!this.tile.equals(that.tile))
        return false;
    }

    boolean this_present_xCoordinate = true;
    boolean that_present_xCoordinate = true;
    if (this_present_xCoordinate || that_present_xCoordinate) {
      if (!(this_present_xCoordinate && that_present_xCoordinate))
        return false;
      if (this.xCoordinate != that.xCoordinate)
        return false;
    }

    boolean this_present_yCoordinate = true;
    boolean that_present_yCoordinate = true;
    if (this_present_yCoordinate || that_present_yCoordinate) {
      if (!(this_present_yCoordinate && that_present_yCoordinate))
        return false;
      if (this.yCoordinate != that.yCoordinate)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(TileState other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    TileState typedOther = (TileState)other;

    lastComparison = Boolean.valueOf(isSetTile()).compareTo(typedOther.isSetTile());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTile()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tile, typedOther.tile);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetXCoordinate()).compareTo(typedOther.isSetXCoordinate());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetXCoordinate()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.xCoordinate, typedOther.xCoordinate);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetYCoordinate()).compareTo(typedOther.isSetYCoordinate());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetYCoordinate()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.yCoordinate, typedOther.yCoordinate);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("TileState(");
    boolean first = true;

    sb.append("tile:");
    if (this.tile == null) {
      sb.append("null");
    } else {
      sb.append(this.tile);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("xCoordinate:");
    sb.append(this.xCoordinate);
    first = false;
    if (!first) sb.append(", ");
    sb.append("yCoordinate:");
    sb.append(this.yCoordinate);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bit_vector = new BitSet(1);
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TileStateStandardSchemeFactory implements SchemeFactory {
    public TileStateStandardScheme getScheme() {
      return new TileStateStandardScheme();
    }
  }

  private static class TileStateStandardScheme extends StandardScheme<TileState> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TileState struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TILE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.tile = Tile.findByValue(iprot.readI32());
              struct.setTileIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // X_COORDINATE
            if (schemeField.type == org.apache.thrift.protocol.TType.BYTE) {
              struct.xCoordinate = iprot.readByte();
              struct.setXCoordinateIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // Y_COORDINATE
            if (schemeField.type == org.apache.thrift.protocol.TType.BYTE) {
              struct.yCoordinate = iprot.readByte();
              struct.setYCoordinateIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TileState struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.tile != null) {
        oprot.writeFieldBegin(TILE_FIELD_DESC);
        oprot.writeI32(struct.tile.getValue());
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(X_COORDINATE_FIELD_DESC);
      oprot.writeByte(struct.xCoordinate);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(Y_COORDINATE_FIELD_DESC);
      oprot.writeByte(struct.yCoordinate);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TileStateTupleSchemeFactory implements SchemeFactory {
    public TileStateTupleScheme getScheme() {
      return new TileStateTupleScheme();
    }
  }

  private static class TileStateTupleScheme extends TupleScheme<TileState> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TileState struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetTile()) {
        optionals.set(0);
      }
      if (struct.isSetXCoordinate()) {
        optionals.set(1);
      }
      if (struct.isSetYCoordinate()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetTile()) {
        oprot.writeI32(struct.tile.getValue());
      }
      if (struct.isSetXCoordinate()) {
        oprot.writeByte(struct.xCoordinate);
      }
      if (struct.isSetYCoordinate()) {
        oprot.writeByte(struct.yCoordinate);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TileState struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.tile = Tile.findByValue(iprot.readI32());
        struct.setTileIsSet(true);
      }
      if (incoming.get(1)) {
        struct.xCoordinate = iprot.readByte();
        struct.setXCoordinateIsSet(true);
      }
      if (incoming.get(2)) {
        struct.yCoordinate = iprot.readByte();
        struct.setYCoordinateIsSet(true);
      }
    }
  }

}

