/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thrift;

public class Constants {

  /**
   * 25 ticks per second at normal rate
   */
  public static final int TICKS_PER_SECOND = 50;

  /**
   * movement takes 5 ticks / tile
   */
  public static final int TICKS_PER_TILE = 10;

  /**
   * normal bomb explodes in 150 ticks (3s)
   * fast bomb in half that time
   * slow bomb takes double that
   */
  public static final int TICKS_BOMB = 150;

}
