/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.riksa.bombah.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum Disease implements org.apache.thrift.TEnum {
  NONE(0),
  FAST_BOMB(1),
  SLOW_BOMB(2),
  NO_BOMB(3),
  FAST(4),
  SLOW(5);

  private final int value;

  private Disease(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Disease findByValue(int value) { 
    switch (value) {
      case 0:
        return NONE;
      case 1:
        return FAST_BOMB;
      case 2:
        return SLOW_BOMB;
      case 3:
        return NO_BOMB;
      case 4:
        return FAST;
      case 5:
        return SLOW;
      default:
        return null;
    }
  }
}
