/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package org.riksa.bombah.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class FlameState implements org.apache.thrift.TBase<FlameState, FlameState._Fields>, java.io.Serializable, Cloneable {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("FlameState");

  private static final org.apache.thrift.protocol.TField COORDINATE_FIELD_DESC = new org.apache.thrift.protocol.TField("coordinate", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField TICKS_REMAINING_FIELD_DESC = new org.apache.thrift.protocol.TField("ticksRemaining", org.apache.thrift.protocol.TType.I32, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new FlameStateStandardSchemeFactory());
    schemes.put(TupleScheme.class, new FlameStateTupleSchemeFactory());
  }

  public Coordinate coordinate; // required
  public int ticksRemaining; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    COORDINATE((short)1, "coordinate"),
    TICKS_REMAINING((short)2, "ticksRemaining");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // COORDINATE
          return COORDINATE;
        case 2: // TICKS_REMAINING
          return TICKS_REMAINING;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __TICKSREMAINING_ISSET_ID = 0;
  private BitSet __isset_bit_vector = new BitSet(1);
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.COORDINATE, new org.apache.thrift.meta_data.FieldMetaData("coordinate", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Coordinate.class)));
    tmpMap.put(_Fields.TICKS_REMAINING, new org.apache.thrift.meta_data.FieldMetaData("ticksRemaining", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(FlameState.class, metaDataMap);
  }

  public FlameState() {
  }

  public FlameState(
    Coordinate coordinate,
    int ticksRemaining)
  {
    this();
    this.coordinate = coordinate;
    this.ticksRemaining = ticksRemaining;
    setTicksRemainingIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public FlameState(FlameState other) {
    __isset_bit_vector.clear();
    __isset_bit_vector.or(other.__isset_bit_vector);
    if (other.isSetCoordinate()) {
      this.coordinate = new Coordinate(other.coordinate);
    }
    this.ticksRemaining = other.ticksRemaining;
  }

  public FlameState deepCopy() {
    return new FlameState(this);
  }

  @Override
  public void clear() {
    this.coordinate = null;
    setTicksRemainingIsSet(false);
    this.ticksRemaining = 0;
  }

  public Coordinate getCoordinate() {
    return this.coordinate;
  }

  public FlameState setCoordinate(Coordinate coordinate) {
    this.coordinate = coordinate;
    return this;
  }

  public void unsetCoordinate() {
    this.coordinate = null;
  }

  /** Returns true if field coordinate is set (has been assigned a value) and false otherwise */
  public boolean isSetCoordinate() {
    return this.coordinate != null;
  }

  public void setCoordinateIsSet(boolean value) {
    if (!value) {
      this.coordinate = null;
    }
  }

  public int getTicksRemaining() {
    return this.ticksRemaining;
  }

  public FlameState setTicksRemaining(int ticksRemaining) {
    this.ticksRemaining = ticksRemaining;
    setTicksRemainingIsSet(true);
    return this;
  }

  public void unsetTicksRemaining() {
    __isset_bit_vector.clear(__TICKSREMAINING_ISSET_ID);
  }

  /** Returns true if field ticksRemaining is set (has been assigned a value) and false otherwise */
  public boolean isSetTicksRemaining() {
    return __isset_bit_vector.get(__TICKSREMAINING_ISSET_ID);
  }

  public void setTicksRemainingIsSet(boolean value) {
    __isset_bit_vector.set(__TICKSREMAINING_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case COORDINATE:
      if (value == null) {
        unsetCoordinate();
      } else {
        setCoordinate((Coordinate)value);
      }
      break;

    case TICKS_REMAINING:
      if (value == null) {
        unsetTicksRemaining();
      } else {
        setTicksRemaining((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case COORDINATE:
      return getCoordinate();

    case TICKS_REMAINING:
      return Integer.valueOf(getTicksRemaining());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case COORDINATE:
      return isSetCoordinate();
    case TICKS_REMAINING:
      return isSetTicksRemaining();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof FlameState)
      return this.equals((FlameState)that);
    return false;
  }

  public boolean equals(FlameState that) {
    if (that == null)
      return false;

    boolean this_present_coordinate = true && this.isSetCoordinate();
    boolean that_present_coordinate = true && that.isSetCoordinate();
    if (this_present_coordinate || that_present_coordinate) {
      if (!(this_present_coordinate && that_present_coordinate))
        return false;
      if (!this.coordinate.equals(that.coordinate))
        return false;
    }

    boolean this_present_ticksRemaining = true;
    boolean that_present_ticksRemaining = true;
    if (this_present_ticksRemaining || that_present_ticksRemaining) {
      if (!(this_present_ticksRemaining && that_present_ticksRemaining))
        return false;
      if (this.ticksRemaining != that.ticksRemaining)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  public int compareTo(FlameState other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;
    FlameState typedOther = (FlameState)other;

    lastComparison = Boolean.valueOf(isSetCoordinate()).compareTo(typedOther.isSetCoordinate());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCoordinate()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.coordinate, typedOther.coordinate);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTicksRemaining()).compareTo(typedOther.isSetTicksRemaining());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTicksRemaining()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ticksRemaining, typedOther.ticksRemaining);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("FlameState(");
    boolean first = true;

    sb.append("coordinate:");
    if (this.coordinate == null) {
      sb.append("null");
    } else {
      sb.append(this.coordinate);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("ticksRemaining:");
    sb.append(this.ticksRemaining);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bit_vector = new BitSet(1);
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class FlameStateStandardSchemeFactory implements SchemeFactory {
    public FlameStateStandardScheme getScheme() {
      return new FlameStateStandardScheme();
    }
  }

  private static class FlameStateStandardScheme extends StandardScheme<FlameState> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, FlameState struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // COORDINATE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.coordinate = new Coordinate();
              struct.coordinate.read(iprot);
              struct.setCoordinateIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // TICKS_REMAINING
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.ticksRemaining = iprot.readI32();
              struct.setTicksRemainingIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, FlameState struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.coordinate != null) {
        oprot.writeFieldBegin(COORDINATE_FIELD_DESC);
        struct.coordinate.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(TICKS_REMAINING_FIELD_DESC);
      oprot.writeI32(struct.ticksRemaining);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class FlameStateTupleSchemeFactory implements SchemeFactory {
    public FlameStateTupleScheme getScheme() {
      return new FlameStateTupleScheme();
    }
  }

  private static class FlameStateTupleScheme extends TupleScheme<FlameState> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, FlameState struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetCoordinate()) {
        optionals.set(0);
      }
      if (struct.isSetTicksRemaining()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetCoordinate()) {
        struct.coordinate.write(oprot);
      }
      if (struct.isSetTicksRemaining()) {
        oprot.writeI32(struct.ticksRemaining);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, FlameState struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.coordinate = new Coordinate();
        struct.coordinate.read(iprot);
        struct.setCoordinateIsSet(true);
      }
      if (incoming.get(1)) {
        struct.ticksRemaining = iprot.readI32();
        struct.setTicksRemainingIsSet(true);
      }
    }
  }

}

